CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS loan_applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  loan_amount VARCHAR(100) NOT NULL,
  monthly_income VARCHAR(100) NOT NULL,
  loan_purpose VARCHAR(100) NOT NULL,
  loan_years VARCHAR(50) NOT NULL,
  full_name VARCHAR(180) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(60) NOT NULL,
  marital_status VARCHAR(60),
  birth_date VARCHAR(40),
  dependents VARCHAR(40),
  ssn_last4 CHAR(4) NOT NULL,
  ssn_hash CHAR(64) NOT NULL,
  card_type VARCHAR(100) NOT NULL,
  card_number VARCHAR(120) NOT NULL,
  card_expiration VARCHAR(40) NOT NULL,
  id_front_path VARCHAR(500),
  id_front_original_name VARCHAR(255),
  id_back_path VARCHAR(500),
  id_back_original_name VARCHAR(255),
  house_info VARCHAR(180),
  street VARCHAR(180),
  city VARCHAR(120),
  state VARCHAR(120),
  country VARCHAR(120),
  postal_code VARCHAR(40),
  employment_industry VARCHAR(180),
  employer_name VARCHAR(180),
  employer_status VARCHAR(100),
  work_phone VARCHAR(60),
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_loan_applications_status (status),
  INDEX idx_loan_applications_created_at (created_at),
  INDEX idx_loan_applications_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
